### ISSUE TITLE
Can not convert type DNetplus_interactiveButtonData

### ISSUE THREAD

**Issue by un-boxing-man** [xXBuilderBXx/DNetPlus#20]
can not convert type DNetplus_interactiveButtonData to Discord.InteractionData
Error	CS0029	Cannot implicitly convert type 'DNetPlus_InteractiveButtons.InteractiveButtonData' to 'Discord.InteractionData'

getting this with your test bot in the repo

**Comment by un-boxing-man** [comment]
![image](https://user-images.githubusercontent.com/54999078/134826868-076704cf-69bc-432a-8340-aad3a56eff53.png)

**Comment by xXBuilderBXx** [comment]
Type is InteractiveButtonData not InteractionData.
